### PR TITLE
Catch async errors

### LINKED ISSUE #11: Handle JS async rejections
Hi again! As part of my port to cljs I realized what could be an issue..maybe.

It seems like at the moment the `continue` protocol only accepts one callback, which makes sense most of the times, the only issue being `js/Promise` rejection.

One could add another callback for errors but I am not myself convinced it is the right thing to do. It would certainly handle [this kind of situation](https://github.com/metosin/sieppari/pull/10/files#diff-65ec7a562ed567eecae608009df7756eR215) that at the moment trigger an uncaught error warning.

Or maybe it is simply better to let it blow and fail fast.

Thoughts?

### PR DESCRIPTION
**Pull request by nilern**
Fixes #11

* Typically async libs complect an error semi-monad with their async semi-monad (JS Promise, Promesa, Manifold). This error handling is essentially async exceptions, and not hooking into it means that we only handle exceptions and put them into `:error` in synchronous usage.
* This branch adds a `catch` method to the `AsyncContext` protocol, which maps directly to the aforementioned async library error handling.
* Some async abstractions like futures and core.async channels have no such error handling strategy. The proposal here is to treat the future or channel yielding an `Exception`/`js/Error` as an async throw. This could be removed if the jury is so inclined, making the `AsyncContext/catch` implementation on those types a no-op.
* A lot of tests are included here, but they are simply analogous to the sync exception catching tests.
* BTW removes the Figwheel test runner obsoleted by #22.

### CODE REVIEW

File: test/cljs/sieppari/native_promise_test.cljs [hunk 1]
```diff
@@ -211,22 +234,3 @@
...
-;;                                                (js/Promise.reject error)))))]
-;;     (async done
-;;       (let [log (atom [])]
-;;         (-> [(make-logging-interceptor log :a)
-;;              (make-rejecting-b log)
-;;              (make-logging-interceptor log :c)
-;;              (make-async-logging-handler log)]
-;;             (sc/execute request
-;;                         fail!
-;;                         fail!))))))
```
Comment (nilern) [inline test/cljs/sieppari/native_promise_test.cljs]: And now we *are* doing something about it!

File: test/cljs/sieppari/native_promise_test.cljs [hunk 2]
```diff
@@ -211,22 +234,3 @@
                           (is (= response :fixed-by-b))
                           (done))
                         fail!))))))
-
-;; At the moment sieppari does not handle async error flows.
-;; We should do something about it probably.
```
Comment (nilern) [inline test/cljs/sieppari/native_promise_test.cljs:216]: And now we *are* doing something about it!

**Review by miikka — APPROVED** [review]
Looks good to me and it makes sense to me to make core.async and futures support `catch` like you have done. Haven't thought about it deeply, though.

@arichiardi, are you still interested in this? What do you think?

**Comment by arichiardi** [comment]
Checking :smile:

File: src/sieppari/util.cljc [hunk 3]
```diff
@@ -0,0 +1,4 @@
+(ns sieppari.util)
```
Comment (arichiardi) [inline src/sieppari/util.cljc:1]: maybe this can live in `sieppari.async` instead of a new namespace, but haven't checked all the usages and not that big of a deal :smile:

**Comment by arichiardi** [comment]
Looks great to me, thanks for tackling this!

**Comment by miikka** [comment]
Let's have it, then.
